Repository PlayCover/PlayCover, pull requests merged in 2022-08, with the labels that each got.

#9 [i18n]: Add and improve zh-Hans translation
  PlayCover/zh-Hans.lproj/Localizable.strings
Labels: localization

#53 Add traditional Chinese translation
  PlayCover/zh-Hant.lproj/Localizable.strings
Labels: localization

#142 Adding Japanese Localization
  PlayCover/en.lproj/Localizable.strings
  PlayCover/ja.lproj/Localizable.strings
Labels: localization

#180 Feat: ✨ Added vertical 720 screen resolution and refactoring to the getter
  PlayCover.xcodeproj/project.pbxproj
  PlayCover/Utils/getScreenSizeSelector.swift
  PlayCover/View/AppSettingsView.swift
  PlayCover/View/PlayAppView.swift
Labels: enhancement

#217 Fixed Traditional Chinese locale
  PlayCover.xcodeproj/project.pbxproj
  PlayCover/en.lproj/Localizable.strings
  PlayCover/zh-Hant.lproj/Localizable.strings
Labels: localization

#207 Feat: ✨ Custom window resolution is here
  PlayCover/Model/AppSettings.swift
  PlayCover/View/AppSettingsView.swift
  PlayCover/View/PlayAppView.swift
  PlayCover/de.lproj/Localizable.strings
  PlayCover/en.lproj/Localizable.strings
  PlayCover/es.lproj/Localizable.strings
  PlayCover/fr.lproj/Localizable.strings
  PlayCover/id.lproj/Localizable.strings
  PlayCover/it.lproj/Localizable.strings
  PlayCover/ja.lproj/Localizable.strings
  PlayCover/ko.lproj/Localizable.strings
  PlayCover/ru.lproj/Localizable.strings
  PlayCover/vi.lproj/Localizable.strings
  PlayCover/zh-Hans.lproj/Localizable.strings
Labels: enhancement

#218 [Localization] NEW: Persian/Farsi (fa_IR)
  PlayCover.xcodeproj/project.pbxproj
  PlayCover/fa-IR.lproj/Localizable.strings
Labels: localization

#220 Translations update from Hosted Weblate
  PlayCover/de.lproj/Localizable.strings
  PlayCover/es.lproj/Localizable.strings
  PlayCover/fa-IR.lproj/Localizable.strings
  PlayCover/fr.lproj/Localizable.strings
  PlayCover/ru.lproj/Localizable.strings
  PlayCover/zh-Hans.lproj/Localizable.strings
  PlayCover/zh-Hant.lproj/Localizable.strings
Labels: localization

#222 Add Arabic locale file
  PlayCover.xcodeproj/project.pbxproj
  PlayCover/ar.lproj/Localizable.strings
Labels: localization

#211 [Enhancement] Enhanced settings view with locale since #202
  PlayCover/View/AppSettingsView.swift
  PlayCover/de.lproj/Localizable.strings
  PlayCover/en.lproj/Localizable.strings
  PlayCover/es.lproj/Localizable.strings
  PlayCover/fa-IR.lproj/Localizable.strings
  PlayCover/fr.lproj/Localizable.strings
  PlayCover/id.lproj/Localizable.strings
  PlayCover/it.lproj/Localizable.strings
  PlayCover/ja.lproj/Localizable.strings
  PlayCover/ko.lproj/Localizable.strings
  PlayCover/ru.lproj/Localizable.strings
  PlayCover/vi.lproj/Localizable.strings
  PlayCover/zh-Hans.lproj/Localizable.strings
  PlayCover/zh-Hant.lproj/Localizable.strings
Labels: enhancement

#230 2.0.0 UI Changes
  Documentation.docc/Documentation.md
  PlayCover.xcodeproj/project.pbxproj
  PlayCover/AppInstaller/Installer.swift
  PlayCover/Documentation.docc/Documentation.md
  PlayCover/Model/AppInfo.swift
  PlayCover/Model/AppSettings.swift
  PlayCover/Model/PlayApp.swift
  PlayCover/Utils/Colors.swift
  PlayCover/Utils/Shell.swift
  PlayCover/View/AppSettingsView.swift
  PlayCover/View/AppsView.swift
  PlayCover/View/InstallSettings.swift
  PlayCover/View/MainView.swift
  PlayCover/View/SetupView.swift
  PlayCover/View/StoreAppView.swift
  PlayCover/View/Style.swift
  PlayCover/ViewModel/AppSettingsVM.swift
  PlayCover/ViewModel/AppsVM.swift
  PlayCover/ViewModel/InstallVM.swift
  PlayCover/ViewModel/StoreVM.swift
  PlayCover/ViewModel/ToastVM.swift
  PlayCover/Views/App Views/PlayAppView.swift
  PlayCover/Views/App Views/StoreAppView.swift
  PlayCover/Views/AppSettingsView.swift
  PlayCover/Views/Genshin Account Views/ChangeGenshinAccountView.swift
  PlayCover/Views/Genshin Account Views/DeleteGenshinAccountView.swift
  PlayCover/Views/Genshin Account Views/StoreGenshinAccountView.swift
  PlayCover/Views/MainView.swift
  PlayCover/Views/MenuBarView.swift
  PlayCover/Views/PlayCoverApp.swift
  PlayCover/Views/Settings/PlayCoverSettingsView.swift
  PlayCover/Views/Settings/UpdateSettings.swift
  PlayCover/Views/Sidebar Views/AppLibraryView.swift
  PlayCover/Views/Sidebar Views/IPALibraryView.swift
  PlayCover/Views/Sparkle.swift
  PlayCover/Views/ToastView.swift
  PlayCover/en.lproj/Localizable.strings
Labels: enhancement

#227 Translations update from Hosted Weblate
  PlayCover/ar.lproj/Localizable.strings
  PlayCover/de.lproj/Localizable.strings
  PlayCover/es.lproj/Localizable.strings
  PlayCover/fa-IR.lproj/Localizable.strings
  PlayCover/fr.lproj/Localizable.strings
  PlayCover/id.lproj/Localizable.strings
  PlayCover/it.lproj/Localizable.strings
  PlayCover/ja.lproj/Localizable.strings
  PlayCover/ko.lproj/Localizable.strings
  PlayCover/ru.lproj/Localizable.strings
  PlayCover/vi.lproj/Localizable.strings
  PlayCover/zh-Hans.lproj/Localizable.strings
  PlayCover/zh-Hant.lproj/Localizable.strings
Labels: localization

#228 Add Ukrainian locale
  PlayCover.xcodeproj/project.pbxproj
  PlayCover/uk.lproj/Localizable.strings
Labels: localization

#266 feat: Add support for new app setting plist
  PlayCover/Model/AppSettings.swift
  PlayCover/Model/Keymapping.swift
  PlayCover/Rules/default.yaml
Labels: enhancement

#49 Implement Discord Activity(Rich Presence)
  PlayCover.xcodeproj/project.pbxproj
  PlayCover/AppInstaller/Utils/Entitlements.swift
  PlayCover/Model/AppSettings.swift
  PlayCover/Model/DiscordActivity.swift
  PlayCover/Views/AppSettingsView.swift
  PlayCover/de.lproj/Localizable.strings
  PlayCover/en.lproj/Localizable.strings
  PlayCover/es.lproj/Localizable.strings
  PlayCover/fr.lproj/Localizable.strings
  PlayCover/id.lproj/Localizable.strings
  PlayCover/it.lproj/Localizable.strings
  PlayCover/ja.lproj/Localizable.strings
  PlayCover/ko.lproj/Localizable.strings
  PlayCover/ru.lproj/Localizable.strings
  PlayCover/vi.lproj/Localizable.strings
  PlayCover/zh-Hans.lproj/Localizable.strings
Labels: enhancement

#242 Translations update from Hosted Weblate
  PlayCover/uk.lproj/Localizable.strings
  PlayCover/zh-Hans.lproj/Localizable.strings
  PlayCover/zh-Hant.lproj/Localizable.strings
Labels: localization

#262 Clean up code and small refactor
  PlayCover/AppInstaller/Installer.swift
  PlayCover/AppInstaller/Utils/Entitlements.swift
  PlayCover/AppInstaller/Utils/IPA.swift
  PlayCover/AppInstaller/Utils/Unarchiver.swift
  PlayCover/IntentFlow/UserIntentFlow.swift
  PlayCover/Model/AppContainer.swift
  PlayCover/Model/AppInfo.swift
  PlayCover/Model/AppSettings.swift
  PlayCover/Model/BaseApp.swift
  PlayCover/Model/Keymapping.swift
  PlayCover/Model/PlayApp.swift
  PlayCover/Model/PlayRules.swift
  PlayCover/PlayCoverError.swift
  PlayCover/Services/NotifyService.swift
  PlayCover/Services/SoundDeviceService.swift
  PlayCover/Utils/DeleteStoredGenshinUserData.swift
  PlayCover/Utils/FileExtensions.swift
  PlayCover/Utils/PlayTools.swift
  PlayCover/Utils/ProcessExtension.swift
  PlayCover/Utils/RestoreGenshinUserData.swift
  PlayCover/Utils/SaveGenshinUserData.swift
  PlayCover/Utils/Shell.swift
  PlayCover/Utils/SystemConfig.swift
  PlayCover/Utils/URLExtensions.swift
  PlayCover/ViewModel/AppsVM.swift
  PlayCover/ViewModel/InstallVM.swift
  PlayCover/ViewModel/Log.swift
  PlayCover/ViewModel/StoreVM.swift
  PlayCover/Views/App Views/PlayAppView.swift
  PlayCover/Views/App Views/StoreAppView.swift
  PlayCover/Views/AppSettingsView.swift
  PlayCover/Views/Genshin Account Views/ChangeGenshinAccountView.swift
  PlayCover/Views/Genshin Account Views/DeleteGenshinAccountView.swift
  PlayCover/Views/Genshin Account Views/StoreGenshinAccountView.swift
  PlayCover/Views/MainView.swift
  PlayCover/Views/MenuBarView.swift
  PlayCover/Views/PlayCoverApp.swift
  PlayCover/Views/Settings/PlayCoverSettingsView.swift
  PlayCover/Views/Settings/UpdateSettings.swift
  PlayCover/Views/Sidebar Views/AppLibraryView.swift
  PlayCover/Views/Sparkle.swift
  PlayCover/Views/ToastView.swift
Labels: enhancement

#258 fix: min width layout appearance
  PlayCover/Views/MainView.swift
Labels: UI

#250 Improve Xcode Command line tools install UX
  PlayCover/Utils/Shell.swift
  PlayCover/Views/MainView.swift
  PlayCover/en.lproj/Localizable.strings
Labels: UI
