Repository PlayCover/PlayCover, pull requests merged in 2022-10, with the labels that each got.

#368 Updated IPA Source Management
  PlayCover.xcodeproj/project.pbxproj
  PlayCover/AppInstaller/Installer.swift
  PlayCover/Model/AppInfo.swift
  PlayCover/Model/PlayApp.swift
  PlayCover/PlayCoverError.swift
  PlayCover/ViewModel/DownloadVM.swift
  PlayCover/ViewModel/NetworkVM.swift
  PlayCover/ViewModel/StoreVM.swift
  PlayCover/ViewModel/ToastVM.swift
  PlayCover/Views/App Views/StoreAppView.swift
  PlayCover/Views/MainView.swift
  PlayCover/Views/MenuBarView.swift
  PlayCover/Views/PlayCoverApp.swift
  PlayCover/Views/Settings/IPASourceSettings.swift
  PlayCover/Views/Settings/PlayCoverSettingsView.swift
  PlayCover/Views/Sidebar Views/AppLibraryView.swift
  PlayCover/Views/Sidebar Views/IPALibraryView.swift
  PlayCover/Views/ToastView.swift
  PlayCover/en.lproj/Localizable.strings
Labels: Squash

#383 App uninstall settings
  PlayCover.xcodeproj/project.pbxproj
  PlayCover/Model/PlayApp.swift
  PlayCover/Views/App Views/PlayAppView.swift
  PlayCover/Views/Settings/PlayCoverSettingsView.swift
  PlayCover/Views/Settings/UninstallSettings.swift
  PlayCover/Views/Uninstaller.swift
  PlayCover/en.lproj/Localizable.strings
Labels: Squash

#413 Install apps without injecting PlayTools
  PlayCover.xcodeproj/project.pbxproj
  PlayCover/AppInstaller/Installer.swift
  PlayCover/Model/BaseApp.swift
  PlayCover/Model/PlayApp.swift
  PlayCover/Utils/PlayTools.swift
  PlayCover/Views/App Views/PlayAppView.swift
  PlayCover/Views/AppSettingsView.swift
  PlayCover/Views/Settings/InstallSettings.swift
  PlayCover/Views/Settings/PlayCoverSettingsView.swift
  PlayCover/en.lproj/Localizable.strings
Labels: Squash

#431 Only allow one window to be opened + Quit when window is closed
  PlayCover/Views/MenuBarView.swift
  PlayCover/Views/PlayCoverApp.swift
Labels: enhancement

#428 Translations update from Hosted Weblate
  PlayCover/ar.lproj/Localizable.strings
  PlayCover/de.lproj/Localizable.strings
  PlayCover/es.lproj/Localizable.strings
  PlayCover/fa.lproj/Localizable.strings
  PlayCover/fr.lproj/Localizable.strings
  PlayCover/id.lproj/Localizable.strings
  PlayCover/it.lproj/Localizable.strings
  PlayCover/ja.lproj/Localizable.strings
  PlayCover/ko.lproj/Localizable.strings
  PlayCover/pt-br.lproj/Localizable.strings
  PlayCover/ru.lproj/Localizable.strings
  PlayCover/uk.lproj/Localizable.strings
  PlayCover/vi.lproj/Localizable.strings
  PlayCover/zh-Hans.lproj/Localizable.strings
  PlayCover/zh-Hant.lproj/Localizable.strings
Labels: localization, Squash
