Repository PlayCover/PlayCover, pull requests merged in 2022-07, with the labels that each got.

#71 Move the app links checkbox into the View menu
  PlayCover/View/AppsView.swift
  PlayCover/View/MenuBarView.swift
  PlayCover/View/PlayCoverApp.swift
  PlayCover/ViewModel/AppsVM.swift
Labels: enhancement

#45 feat: Implement Sparkle Updater
  .github/workflows/2.nightly_release.yml
  PlayCover.xcodeproj/project.pbxproj
  PlayCover/Info.plist
  PlayCover/Services/UpdateService.swift
  PlayCover/View/MainView.swift
  PlayCover/View/MenuBarView.swift
  PlayCover/View/PlayCoverApp.swift
  PlayCover/View/Settings/PlayCoverSettingsView.swift
  PlayCover/View/Settings/UpdateSettings.swift
  PlayCover/View/Sparkle.swift
Labels: enhancement

#108 Adding account management for Genshin and windowed fullscreen menu
  PlayCover.xcodeproj/project.pbxproj
  PlayCover/Model/AppSettings.swift
  PlayCover/Utils/DeleteStoredGenshinUserData.swift
  PlayCover/Utils/RestoreGenshinUserData.swift
  PlayCover/Utils/SaveGenshinUserData.swift
  PlayCover/Utils/Shell.swift
  PlayCover/View/AppSettingsView.swift
  PlayCover/View/ChangeGenshinAccountView.swift
  PlayCover/View/DeleteGenshinStoredAccountView.swift
  PlayCover/View/PlayAppView.swift
  PlayCover/View/StoreGenshinAccountView.swift
  PlayCover/View/Style.swift
Labels: enhancement

#113 Updated info, instructions, and grammar in Readme
  README.md
Labels: documentation

#86 Revamped localization system (much more accurate and up to date)
  .gitignore
  PlayCover/Model/StoreApp.swift
  PlayCover/Services/SoundDeviceService.swift
  PlayCover/View/AppSettingsView.swift
  PlayCover/View/ChangeGenshinAccountView.swift
  PlayCover/View/DeleteGenshinStoredAccountView.swift
  PlayCover/View/MainView.swift
  PlayCover/View/MenuBarView.swift
  PlayCover/View/PlayAppView.swift
  PlayCover/View/PlayCoverApp.swift
  PlayCover/View/SetupView.swift
  PlayCover/View/Sparkle.swift
  PlayCover/View/StoreGenshinAccountView.swift
  PlayCover/View/Style.swift
  PlayCover/ViewModel/InstallVM.swift
  PlayCover/ViewModel/Log.swift
  PlayCover/de.lproj/Localizable.strings
  PlayCover/en.lproj/Localizable.strings
  PlayCover/es.lproj/Localizable.strings
  PlayCover/fr.lproj/Localizable.strings
  PlayCover/id.lproj/Localizable.strings
  PlayCover/it.lproj/Localizable.strings
  PlayCover/ja.lproj/Localizable.strings
  PlayCover/ko.lproj/Localizable.strings
  PlayCover/ru.lproj/Localizable.strings
  PlayCover/vi.lproj/Localizable.strings
  PlayCover/zh-Hans.lproj/Localizable.strings
Labels: localization
