Repository PlayCover/PlayCover, pull requests merged in 2022-09, with the labels that each got.

#302 Remove `isGame` and update locale
  PlayCover/Model/AppInfo.swift
  PlayCover/Views/App Views/PlayAppView.swift
  PlayCover/Views/AppSettingsView.swift
  PlayCover/en.lproj/Localizable.strings
Labels: localization

#123 Changed nightly branch logo
  .github/workflows/2.nightly_release.yml
  PlayCover.xcodeproj/project.pbxproj
  PlayCover.xcodeproj/xcshareddata/xcschemes/PlayCover.xcscheme
  PlayCover/Assets.xcassets/AppIcon.appiconset/128@2x.png
  PlayCover/Assets.xcassets/AppIcon.appiconset/128R128x1.png
  PlayCover/Assets.xcassets/AppIcon.appiconset/16@2x.png
  PlayCover/Assets.xcassets/AppIcon.appiconset/16R64x1.png
  PlayCover/Assets.xcassets/AppIcon.appiconset/256@2x.png
  PlayCover/Assets.xcassets/AppIcon.appiconset/256R256x1.png
  PlayCover/Assets.xcassets/AppIcon.appiconset/32@2x.png
  PlayCover/Assets.xcassets/AppIcon.appiconset/32R64x1.png
  PlayCover/Assets.xcassets/AppIcon.appiconset/512@2x.png
  PlayCover/Assets.xcassets/AppIcon.appiconset/512R512x1.png
  PlayCover/Assets.xcassets/AppIcon.dev.appiconset/128@2x.png
  PlayCover/Assets.xcassets/AppIcon.dev.appiconset/128R128x1.png
  PlayCover/Assets.xcassets/AppIcon.dev.appiconset/16@2x.png
  PlayCover/Assets.xcassets/AppIcon.dev.appiconset/16R64x1.png
  PlayCover/Assets.xcassets/AppIcon.dev.appiconset/256@2x.png
  PlayCover/Assets.xcassets/AppIcon.dev.appiconset/256R256x1.png
  PlayCover/Assets.xcassets/AppIcon.dev.appiconset/32@2x.png
  PlayCover/Assets.xcassets/AppIcon.dev.appiconset/32R64x1.png
  PlayCover/Assets.xcassets/AppIcon.dev.appiconset/512@2x.png
  PlayCover/Assets.xcassets/AppIcon.dev.appiconset/512R512x1.png
  PlayCover/Assets.xcassets/AppIcon.dev.appiconset/Contents.json
  fastlane/Fastfile
Labels: enhancement

#331 Fix automatic screen size detection
  PlayCover/Model/AppSettings.swift
  PlayCover/Views/AppSettingsView.swift
  PlayCover/en.lproj/Localizable.strings
Labels: bug, enhancement

#327 Code cleanup: removal of old resolution selector
  PlayCover/Utils/ScreenSizeSelector.swift
  PlayCover/Utils/SetScreenSize.swift
Labels: enhancement

#330 Translations update from Hosted Weblate
  PlayCover/ar.lproj/Localizable.strings
  PlayCover/de.lproj/Localizable.strings
  PlayCover/es.lproj/Localizable.strings
  PlayCover/fa-IR.lproj/Localizable.strings
  PlayCover/fr.lproj/Localizable.strings
  PlayCover/id.lproj/Localizable.strings
  PlayCover/it.lproj/Localizable.strings
  PlayCover/ja.lproj/Localizable.strings
  PlayCover/ko.lproj/Localizable.strings
  PlayCover/ru.lproj/Localizable.strings
  PlayCover/uk.lproj/Localizable.strings
  PlayCover/vi.lproj/Localizable.strings
  PlayCover/zh-Hans.lproj/Localizable.strings
  PlayCover/zh-Hant.lproj/Localizable.strings
Labels: localization

#344 [Localization] NEW: Portuguese/Brazil (pt-br)
  PlayCover.xcodeproj/project.pbxproj
  PlayCover/pt-br.lproj/Localizable.strings
Labels: localization
