Repository PlayCover/PlayCover, pull requests merged in 2023-12, with the labels that each got.

#1131 Fix sidebar button
  PlayCover/Views/MainView.swift
Labels: UI

#1243 fix: missing semi-colon in en localisation
  PlayCover/en.lproj/Localizable.strings
Labels: localization

#1100 Use Application ID when storing apps
  PlayCover/AppInstaller/Installer.swift
  PlayCover/Model/PlayApp.swift
  PlayCover/Utils/Extensions/PlayAppExtensions.swift
  PlayCover/ViewModel/AppsVM.swift
  PlayCover/Views/AppSettingsView.swift
  PlayCover/Views/Uninstaller.swift
  PlayCover/en.lproj/Localizable.strings
Labels: enhancement, help wanted / caution, Squash

#1000 Translations update from Hosted Weblate
  PlayCover/da.lproj/Localizable.strings
  PlayCover/de.lproj/Localizable.strings
  PlayCover/es.lproj/Localizable.strings
  PlayCover/fa.lproj/Localizable.strings
  PlayCover/fr.lproj/Localizable.strings
  PlayCover/hi.lproj/Localizable.strings
  PlayCover/id.lproj/Localizable.strings
  PlayCover/ja.lproj/Localizable.strings
  PlayCover/ko.lproj/Localizable.strings
  PlayCover/pt-br.lproj/Localizable.strings
  PlayCover/ro.lproj/Localizable.strings
  PlayCover/ru.lproj/Localizable.strings
  PlayCover/tr.lproj/Localizable.strings
  PlayCover/vi.lproj/Localizable.strings
  PlayCover/zh-Hans.lproj/Localizable.strings
  PlayCover/zh-Hant.lproj/Localizable.strings
Labels: localization, Squash

#1288 revert build file + fix deprecation
  .github/workflows/1.build_release.yml
Labels: squash
