Repository PlayCover/PlayCover, pull requests merged in 2023-03, with the labels that each got.

#827 Reinstate XCLT
  PlayCover.xcodeproj/project.pbxproj
  PlayCover/AppInstaller/Installer.swift
  PlayCover/Model/PlayApp.swift
  PlayCover/PlayCoverError.swift
  PlayCover/Utils/Extensions/DataExtensions.swift
  PlayCover/Utils/Extensions/FileExtensions.swift
  PlayCover/Utils/Extensions/URLExtensions.swift
  PlayCover/Utils/PlayTools.swift
  PlayCover/Utils/Shell.swift
  PlayCover/Views/MainView.swift
  PlayCover/Views/PlayCoverApp.swift
  PlayCover/en.lproj/Localizable.strings
  scripts/xcode_install.scpt
Labels: help wanted / caution, Squash

#839 HTTP code check
  PlayCover/AppInstaller/Downloader.swift
  PlayCover/Model/ITunesResponse.swift
  PlayCover/ViewModel/NetworkVM.swift
  PlayCover/ViewModel/StoreVM.swift
  PlayCover/Views/Settings/IPASourceSettings.swift
  PlayCover/en.lproj/Localizable.strings
Labels: Squash

#844 Translations update from Hosted Weblate
  PlayCover/da.lproj/Localizable.strings
  PlayCover/de.lproj/Localizable.strings
  PlayCover/es.lproj/Localizable.strings
  PlayCover/fa.lproj/Localizable.strings
  PlayCover/fr.lproj/Localizable.strings
  PlayCover/hi.lproj/Localizable.strings
  PlayCover/id.lproj/Localizable.strings
  PlayCover/ja.lproj/Localizable.strings
  PlayCover/ko.lproj/Localizable.strings
  PlayCover/pt-br.lproj/Localizable.strings
  PlayCover/ro.lproj/Localizable.strings
  PlayCover/ru.lproj/Localizable.strings
  PlayCover/tr.lproj/Localizable.strings
  PlayCover/vi.lproj/Localizable.strings
  PlayCover/zh-Hans.lproj/Localizable.strings
  PlayCover/zh-Hant.lproj/Localizable.strings
Labels: localization, Squash

#753 Add `force_unwrapping` rule to SwiftLint
  .swiftlint.yml
  PlayCover.xcodeproj/project.pbxproj
  PlayCover/AppInstaller/Downloader.swift
  PlayCover/AppInstaller/Installer.swift
  PlayCover/IntentFlow/UserIntentFlow.swift
  PlayCover/Model/AppInfo.swift
  PlayCover/Model/PlayApp.swift
  PlayCover/Model/PlayRules.swift
  PlayCover/Utils/AppIntegrity.swift
  PlayCover/Utils/Entitlements.swift
  PlayCover/Utils/Extensions/DataExtensions.swift
  PlayCover/Utils/Extensions/FileExtensions.swift
  PlayCover/Utils/IPA.swift
  PlayCover/Utils/PlayTools.swift
  PlayCover/Utils/Shell.swift
  PlayCover/Utils/SystemConfig.swift
  PlayCover/ViewModel/AppsVM.swift
  PlayCover/ViewModel/StoreVM.swift
  PlayCover/Views/App Views/StoreAppView.swift
  PlayCover/Views/MainView.swift
  PlayCover/Views/MenuBarView.swift
  PlayCover/Views/Settings/IPASourceSettings.swift
  PlayCover/Views/Sidebar Views/AppLibraryView.swift
  PlayCover/Views/Sidebar Views/IPALibraryView.swift
  PlayCover/Views/SigningSetupView.swift
  PlayCover/Views/Uninstaller.swift
Labels: Squash

#860 Fix XCLT-less Installer
  PlayCover.xcodeproj/project.pbxproj
  PlayCover/AppInstaller/Installer.swift
  PlayCover/Model/PlayApp.swift
  PlayCover/Utils/Extensions/DataExtensions.swift
  PlayCover/Utils/Macho.swift
  PlayCover/Utils/PlayTools.swift
Labels: Squash
