Repository PlayCover/PlayCover, pull requests merged in 2023-04, with the labels that each got.

#791 feat!: KeyCover keychain encryption for PlayChain
  PlayCover.xcodeproj/project.pbxproj
  PlayCover/Model/PlayApp.swift
  PlayCover/Utils/KeyCover.swift
  PlayCover/Views/App Views/PlayAppView.swift
  PlayCover/Views/KeyCoverSetupViews.swift
  PlayCover/Views/KeyCoverViews.swift
  PlayCover/Views/MainView.swift
  PlayCover/Views/PlayCoverApp.swift
  PlayCover/Views/Settings/KeyCoverSettings.swift
  PlayCover/Views/Settings/PlayCoverSettingsView.swift
  PlayCover/Views/Uninstaller.swift
  PlayCover/en.lproj/Localizable.strings
Labels: enhancement, help wanted / caution, Squash

#909 Simplify brew instructions
  README.md
Labels: documentation

#807 Add localization in app
  PlayCover/Utils/PlayTools.swift
Labels: Squash
