Repository PlayCover/PlayCover, pull requests merged in 2023-01, with the labels that each got.

#678 Fix toast view appearance duration
  PlayCover/Views/ToastView.swift
Labels: UI

#640 Adjust README for 2.0.0
  README.md
  images/dark.png
  images/light.png
Labels: Squash

#685 Escape forwards slash
  PlayCover/AppInstaller/Installer.swift
  PlayCover/AppInstaller/Utils/IPA.swift
  PlayCover/Model/AppContainer.swift
  PlayCover/Model/AppSettings.swift
  PlayCover/Model/BaseApp.swift
  PlayCover/Model/PlayApp.swift
  PlayCover/Utils/DeletePreferences.swift
  PlayCover/Utils/GenshinUserData/DeleteStoredGenshinUserData.swift
  PlayCover/Utils/GenshinUserData/RestoreGenshinUserData.swift
  PlayCover/Utils/GenshinUserData/SaveGenshinUserData.swift
  PlayCover/Utils/Shell.swift
  PlayCover/Utils/URLExtensions.swift
Labels: enhancement

#681 Translations update from Hosted Weblate
  PlayCover/de.lproj/Localizable.strings
  PlayCover/fr.lproj/Localizable.strings
  PlayCover/hi.lproj/Localizable.strings
  PlayCover/ja.lproj/Localizable.strings
  PlayCover/ko.lproj/Localizable.strings
  PlayCover/pt-br.lproj/Localizable.strings
  PlayCover/zh-Hans.lproj/Localizable.strings
  PlayCover/zh-Hant.lproj/Localizable.strings
Labels: localization, Squash

#663 Improve misc settings format
  PlayCover/Views/AppSettingsView.swift
  PlayCover/en.lproj/Localizable.strings
Labels: UI

#625 Fancy IPA Library
  PlayCover.xcodeproj/project.pbxproj
  PlayCover/Utils/Cacher.swift
  PlayCover/Utils/ViewExtenstions.swift
  PlayCover/ViewModel/StoreVM.swift
  PlayCover/Views/App Views/DetailStoreAppView.swift
  PlayCover/Views/App Views/PlayAppView.swift
  PlayCover/Views/App Views/StoreAppView.swift
  PlayCover/Views/MenuBarView.swift
  PlayCover/Views/Sidebar Views/IPALibraryView.swift
  PlayCover/en.lproj/Localizable.strings
Labels: enhancement, help wanted / caution, UI, Squash

#704 Translations update from Hosted Weblate
  PlayCover/de.lproj/Localizable.strings
  PlayCover/es.lproj/Localizable.strings
  PlayCover/fa.lproj/Localizable.strings
  PlayCover/fr.lproj/Localizable.strings
  PlayCover/hi.lproj/Localizable.strings
  PlayCover/id.lproj/Localizable.strings
  PlayCover/ja.lproj/Localizable.strings
  PlayCover/ko.lproj/Localizable.strings
  PlayCover/pt-br.lproj/Localizable.strings
  PlayCover/ro.lproj/Localizable.strings
  PlayCover/ru.lproj/Localizable.strings
  PlayCover/tr.lproj/Localizable.strings
  PlayCover/vi.lproj/Localizable.strings
  PlayCover/zh-Hans.lproj/Localizable.strings
  PlayCover/zh-Hant.lproj/Localizable.strings
Labels: localization

#706 Add Catalan
  PlayCover.xcodeproj/project.pbxproj
  PlayCover/ca.lproj/Localizable.strings
Labels: localization

#661 fixed issue where the command tools wont be recognized if terminal/zs…
  PlayCover/Utils/Shell.swift
Labels: Squash

#711 Remove Xcode CLI Dependancy
  PlayCover.xcodeproj/project.pbxproj
  PlayCover/AppInstaller/Installer.swift
  PlayCover/Model/PlayApp.swift
  PlayCover/PlayCoverError.swift
  PlayCover/Utils/DataExtensions.swift
  PlayCover/Utils/FileExtensions.swift
  PlayCover/Utils/PlayTools.swift
  PlayCover/Utils/URLExtensions.swift
  PlayCover/en.lproj/Localizable.strings
Labels: Squash

#713 Translations update from Hosted Weblate
  PlayCover/ca.lproj/Localizable.strings
  PlayCover/de.lproj/Localizable.strings
  PlayCover/es.lproj/Localizable.strings
  PlayCover/fa.lproj/Localizable.strings
  PlayCover/fr.lproj/Localizable.strings
  PlayCover/hi.lproj/Localizable.strings
  PlayCover/id.lproj/Localizable.strings
  PlayCover/ja.lproj/Localizable.strings
  PlayCover/ko.lproj/Localizable.strings
  PlayCover/pt-br.lproj/Localizable.strings
  PlayCover/ro.lproj/Localizable.strings
  PlayCover/ru.lproj/Localizable.strings
  PlayCover/tr.lproj/Localizable.strings
  PlayCover/vi.lproj/Localizable.strings
  PlayCover/zh-Hans.lproj/Localizable.strings
  PlayCover/zh-Hant.lproj/Localizable.strings
Labels: localization, Squash

#743 3.0.0 Cleanup
  PlayCover.xcodeproj/project.pbxproj
  PlayCover/Model/AppSettings.swift
  PlayCover/Utils/DefaultFileApp.m
  PlayCover/Utils/DeletePreferences.swift
  PlayCover/Utils/Entitlements.swift
  PlayCover/Utils/Extensions/DataExtensions.swift
  PlayCover/Utils/Extensions/FileExtensions.swift
  PlayCover/Utils/Extensions/URLExtensions.swift
  PlayCover/Utils/IPA.swift
  PlayCover/Utils/PlayTools.swift
  PlayCover/Utils/ProcessExtension.swift
  PlayCover/Utils/Shell.swift
  PlayCover/Views/App Views/PlayAppView.swift
  PlayCover/Views/AppSettingsView.swift
  PlayCover/Views/Sidebar Views/IPALibraryView.swift
  PlayCover/en.lproj/Localizable.strings
  PlayCover/input.xcfilelist
  PlayCover/output.xcfilelist
  scripts/bootstrap.sh
  scripts/cp_frameworks.sh
Labels: Squash

#740 Feat: add invisible app alias
  PlayCover/Model/PlayApp.swift
  PlayCover/Views/AppSettingsView.swift
  PlayCover/Views/Uninstaller.swift
  PlayCover/en.lproj/Localizable.strings
Labels: enhancement, Squash

#705 Download checksum
  PlayCover.xcodeproj/project.pbxproj
  PlayCover/AppInstaller/Downloader.swift
  PlayCover/ViewModel/DownloadVM.swift
  PlayCover/ViewModel/InstallVM.swift
  PlayCover/ViewModel/ProgressVM.swift
  PlayCover/ViewModel/StoreVM.swift
  PlayCover/Views/App Views/StoreAppView.swift
  PlayCover/Views/MenuBarView.swift
  PlayCover/Views/PlayCoverApp.swift
  PlayCover/Views/Sidebar Views/AppLibraryView.swift
  PlayCover/Views/ToastView.swift
  PlayCover/de.lproj/Localizable.strings
  PlayCover/en.lproj/Localizable.strings
  PlayCover/es.lproj/Localizable.strings
  PlayCover/fa.lproj/Localizable.strings
  PlayCover/fr.lproj/Localizable.strings
  PlayCover/hi.lproj/Localizable.strings
  PlayCover/id.lproj/Localizable.strings
  PlayCover/ja.lproj/Localizable.strings
  PlayCover/ko.lproj/Localizable.strings
  PlayCover/pt-br.lproj/Localizable.strings
  PlayCover/ro.lproj/Localizable.strings
  PlayCover/ru.lproj/Localizable.strings
  PlayCover/tr.lproj/Localizable.strings
  PlayCover/vi.lproj/Localizable.strings
  PlayCover/zh-Hans.lproj/Localizable.strings
  PlayCover/zh-Hant.lproj/Localizable.strings
Labels: enhancement, Squash
