Repository PlayCover/PlayCover, pull requests merged in 2023-02, with the labels that each got.

#764 Translations update from Hosted Weblate
  PlayCover/ca.lproj/Localizable.strings
  PlayCover/de.lproj/Localizable.strings
  PlayCover/es.lproj/Localizable.strings
  PlayCover/fa.lproj/Localizable.strings
  PlayCover/fr.lproj/Localizable.strings
  PlayCover/hi.lproj/Localizable.strings
  PlayCover/id.lproj/Localizable.strings
  PlayCover/ja.lproj/Localizable.strings
  PlayCover/ko.lproj/Localizable.strings
  PlayCover/pt-br.lproj/Localizable.strings
  PlayCover/ro.lproj/Localizable.strings
  PlayCover/ru.lproj/Localizable.strings
  PlayCover/tr.lproj/Localizable.strings
  PlayCover/vi.lproj/Localizable.strings
  PlayCover/zh-Hans.lproj/Localizable.strings
  PlayCover/zh-Hant.lproj/Localizable.strings
Labels: Squash

#538 feat: (slightly) more robust uri handler
  PlayCover.xcodeproj/project.pbxproj
  PlayCover/Utils/URLHandler.swift
  PlayCover/Views/MainView.swift
  PlayCover/Views/PlayCoverApp.swift
  PlayCover/Views/Settings/IPASourceSettings.swift
  PlayCover/Views/Sidebar Views/IPALibraryView.swift
Labels: enhancement, help wanted / caution, Squash

#803 Translations update from Hosted Weblate
  PlayCover/ca.lproj/Localizable.strings
  PlayCover/de.lproj/Localizable.strings
  PlayCover/es.lproj/Localizable.strings
  PlayCover/fa.lproj/Localizable.strings
  PlayCover/fr.lproj/Localizable.strings
  PlayCover/hi.lproj/Localizable.strings
  PlayCover/id.lproj/Localizable.strings
  PlayCover/ja.lproj/Localizable.strings
  PlayCover/ko.lproj/Localizable.strings
  PlayCover/pt-br.lproj/Localizable.strings
  PlayCover/ro.lproj/Localizable.strings
  PlayCover/ru.lproj/Localizable.strings
  PlayCover/tr.lproj/Localizable.strings
  PlayCover/vi.lproj/Localizable.strings
  PlayCover/zh-Hans.lproj/Localizable.strings
  PlayCover/zh-Hant.lproj/Localizable.strings
Labels: localization, Squash
