Repository PlayCover/PlayCover, pull requests merged in 2024-08, with the labels that each got.

#1563 Translations update from Hosted Weblate
  PlayCover/ar.lproj/Localizable.strings
  PlayCover/ca.lproj/Localizable.strings
  PlayCover/de.lproj/Localizable.strings
  PlayCover/es.lproj/Localizable.strings
  PlayCover/it.lproj/Localizable.strings
  PlayCover/ja.lproj/Localizable.strings
  PlayCover/ru.lproj/Localizable.strings
  PlayCover/uk.lproj/Localizable.strings
  PlayCover/vi.lproj/Localizable.strings
Labels: localization, squash

#1502 Download Prohibited apps
  PlayCover/AppInstaller/Downloader.swift
  PlayCover/en.lproj/Localizable.strings
Labels: squash

#1543 Check if app has macOS native version
  PlayCover/AppInstaller/Downloader.swift
  PlayCover/AppInstaller/Installer.swift
  PlayCover/Utils/Extensions/PlayAppExtensions.swift
  PlayCover/Utils/IPA.swift
  PlayCover/en.lproj/Localizable.strings
Labels: squash

#1592 Feat: SourceFolders
  Cartfile.resolved
  PlayCover.xcodeproj/project.pbxproj
  PlayCover/AppInstaller/Downloader.swift
  PlayCover/ViewModel/DownloadVM.swift
  PlayCover/ViewModel/StoreAppVM.swift
  PlayCover/ViewModel/StoreVM.swift
  PlayCover/Views/App Views/StoreAppView.swift
  PlayCover/Views/MainView.swift
  PlayCover/Views/Settings/IPASourceSettings.swift
  PlayCover/Views/Sidebar Views/AppLibraryView.swift
  PlayCover/Views/Sidebar Views/IPALibraryView.swift
  PlayCover/Views/Sidebar Views/IPASourceView.swift
  PlayCover/Views/StoreInfoAppView.swift
  PlayCover/en.lproj/Localizable.strings
Labels: enhancement, UI, squash
