Repository PlayCover/PlayCover, pull requests merged in 2024-06, with the labels that each got.

#1459 Added Italian Localizable.strings
  PlayCover/it.lproj/Localizable.strings
Labels: localization

#1207 Added store app icon load timeout
  PlayCover/Views/App Views/StoreAppView.swift
Labels: UI, squash

#1176 IPA library app info
  PlayCover.xcodeproj/project.pbxproj
  PlayCover/ViewModel/NetworkVM.swift
  PlayCover/ViewModel/StoreAppVM.swift
  PlayCover/Views/App Views/StoreAppView.swift
  PlayCover/Views/MainView.swift
  PlayCover/Views/Sidebar Views/IPALibraryView.swift
  PlayCover/Views/StoreInfoAppView.swift
  PlayCover/en.lproj/Localizable.strings
Labels: enhancement, UI

#1472 Google drive hosted IPA
  PlayCover.xcodeproj/project.pbxproj
  PlayCover/Utils/GoogleDrive.swift
  PlayCover/Views/App Views/StoreAppView.swift
Labels: squash
