Repository PlayCover/PlayCover, pull requests merged in 2024-09, with the labels that each got.

#1653 Translations update from Hosted Weblate
  PlayCover/ar.lproj/Localizable.strings
  PlayCover/ca.lproj/Localizable.strings
  PlayCover/da.lproj/Localizable.strings
  PlayCover/de.lproj/Localizable.strings
  PlayCover/es.lproj/Localizable.strings
  PlayCover/fa.lproj/Localizable.strings
  PlayCover/fr.lproj/Localizable.strings
  PlayCover/hi.lproj/Localizable.strings
  PlayCover/id.lproj/Localizable.strings
  PlayCover/it.lproj/Localizable.strings
  PlayCover/ja.lproj/Localizable.strings
  PlayCover/ko.lproj/Localizable.strings
  PlayCover/pt-br.lproj/Localizable.strings
  PlayCover/ro.lproj/Localizable.strings
  PlayCover/ru.lproj/Localizable.strings
  PlayCover/tr.lproj/Localizable.strings
  PlayCover/uk.lproj/Localizable.strings
  PlayCover/vi.lproj/Localizable.strings
  PlayCover/zh-Hans.lproj/Localizable.strings
  PlayCover/zh-Hant.lproj/Localizable.strings
Labels: localization, squash

#1687 Fix (Temp): Sidebar Navigation Deselection on Sequoia
  PlayCover/Views/MainView.swift
Labels: UI

#1675 fix link
  PlayCover/Views/MenuBarView.swift
Labels: documentation
